# Generated by Django 4.0.4 on 2022-06-03 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Mobile', models.BigIntegerField(default='')),
                ('balance', models.FloatField(default=8)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
